---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Update cache of APT 
  apt: update_cache=yes

- name: Install common apt packages
  apt: pkg={{ item }} state=latest
  with_items: elk_common_packages
  sudo: yes

- name: Monit conf file
  copy:
    src=monitrc
    dest=/etc/monit/monitrc
    owner=root group=root mode=600
  sudo: yes
  notify: Restart monit

- name: Install Java
  include: java.yml

- name: ES apt GPG key
  apt_key:
    url='http://packages.elasticsearch.org/GPG-KEY-elasticsearch'
  when: ansible_os_family == 'Debian'
  sudo: yes

- name: Install Elasticsearch
  include: elasticsearch.yml

- name: Install Logstash
  include: logstash.yml

- name: Install Nginx
  include: nginx.yml

- name: Install Kibana
  include: kibana.yml
